name: 🤖 Build & Push Backend Services

on:
  push:
    branches: [main]
    paths:
      - 'actions/**'
  workflow_dispatch:

jobs:
  build-action-server:
    name: Build & Push Rasa Action Server
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Rasa Action Server image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/opspilot-backend:latest -f Dockerfile.actions .

      - name: Push Rasa Action Server image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/opspilot-backend:latest
          