name: 🤖 Build & Push Frontend Service

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-rasa-frontend:
    name: Build & Push OpsPilot Frontend
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend image
        run: |
          cd frontend
          docker build -t ghcr.io/${{ github.repository_owner }}/opspilot-frontend:latest .

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/opspilot-frontend:latest
