name: Train & Publish Model/API

on:
  push:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.9'

      - name: Cache Poetry & pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry & configure venv
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run training script
        run: |
          chmod +x scripts/train_model.sh
          ./scripts/train_model.sh

#      - name: Upload trained models
#        uses: actions/upload-artifact@v3
#        with:
#          name: models
#          path: models/
#          retention-days: 7
  publish_model:
    name: Publish Latest Model as Release Asset
    needs: train_model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create or update "model-latest" release
        uses: ncipollo/release-action@v1
        with:
          tag: model-latest
          release_name: "Latest Trained Model"
          files: |
            models/**
          overwrite: true

  push_rasa_image:
    name: Push Rasa API Image to GHCR
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Rasa image from Docker Hub
        run: docker pull rasa/rasa:3.6.21-full

      - name: Retag for GHCR
        run: |
          docker tag \
            rasa/rasa:3.6.21-full \
            ghcr.io/${{ github.repository_owner }}/rasa:3.6.21-full

      - name: Push to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/rasa:3.6.21-full
