name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: docker
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    container: docker:latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          set -e
          cd frontend
          docker build -t rasa-chatbot-frontend .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Test Placeholder
        run: echo "test"

  train-model:
    name: Train Rasa Model
    runs-on: ubuntu-latest
    needs: build-frontend
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: "false"

      - name: Train Model
        run: |
          chmod +x scripts/train_model.sh
          ./scripts/train_model.sh

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: rasa-model
          path: models/
          retention-days: 7
