name: Security Checks

on:
  push:
    branches:
      - main

jobs:
  owasp_dependency_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (for OWASP Dependency-Check)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download OWASP Dependency-Check CLI
        run: |
          VERSION=8.4.1
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v${VERSION}/dependency-check-${VERSION}-release.zip
          unzip dependency-check-${VERSION}-release.zip -d dependency-check

      - name: Run OWASP Dependency-Check
        run: |
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh
          mkdir -p owasp-report
          dependency-check/dependency-check/bin/dependency-check.sh \
            --project "frontend" \
            --scan "./frontend" \
            --format "HTML" \
            --format "XML" \
            --format "JSON" \
            --out "owasp-report"

      - name: Upload OWASP reports
        uses: actions/upload-artifact@v4
        with:
          name: owasp-reports
          path: owasp-report/
